name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World Action
        uses: ./.github/actions/hello-world
        with:
          name: "Sérgio Rebelo"
